### ISSUE TITLE
A bug in Describe >Multivariate>Principal Component Analysis dialog

### ISSUE THREAD

**Issue by Vitalis95** [IDEMSInternational/R-Instat#7327]
Here is the dialog,
I have used `decathlon` data from `FactoMineR` package

![image](https://user-images.githubusercontent.com/89011415/159885089-7ea50a80-3fba-42e3-adec-bbc0dadcfc88.png)

 When I click `OK` , I get the following bug;

![image](https://user-images.githubusercontent.com/89011415/159874842-657fd268-aa67-4647-928c-83b6aef9be1d.png)

When I ran the R-Script generated in RStudio,  it works fine and output is generated.
@rdstern @shadrackkibet @N-thony

**Comment by N-thony** [comment]
@Vitalis95 is this bug fixed now?

**Comment by Vitalis95** [comment]
@N-thony , the bug is still there although output is produced

![image](https://user-images.githubusercontent.com/89011415/172351888-613ac1ed-230c-4bac-b744-ff02f688bd4c.png)

**Comment by rdstern** [comment]
@Vitalis95 I suggest you hang on a few minutes, while I clarify issue #7318 .  Then check that the bug is fixed in the extended dialogue.

**Comment by lilyclements** [comment]
This is now working - and the dlg looks slightly different. I would assume that the suggestion from @rdstern that it'll be fixed after clarifying #7318 held true
