### ISSUE TITLE
Small bug in Prepare > Data Frame > Insert Columns/Rows dialog

### ISSUE THREAD

**Issue by rdstern** [IDEMSInternational/R-Instat#9485]
@lilyclements This is to add extra columns or rows.  The columns seems to be ok.  For rows I get:

![Image](https://github.com/user-attachments/assets/13fd852f-6456-4ce1-8d16-ee76fb5f05b4)

This was straight after running the test version - so even without updating the packages to the latest versions.  So perhaps it has been fixed?

**Comment by lilyclements** [comment]
@rdstern great, thanks. Fixed in the `databook` package [here](https://github.com/IDEMSInternational/databook/pull/49)

**Comment by rdstern** [comment]
@lilyclements ok, eventually.
a) I detached in R-Instat and then installed databook.  Seemed ok but the error persisted.
b) So I detached again and then installed from RStudio, which seemed to work also.
c) Now it works.  What else should I test?
d) Could you change the number when you update?  It is still always 0.1.5, and whether the updating has worked would be easier if the number kept changing.  Is that difficult?

**Comment by lilyclements** [comment]
@rdstern to d), I will make sure I update the version in the future. Thanks!
Otherwise are we happy for this to be closed?
Note that I have started unit testing on the packages -- instatCalculations is complete, and I've nearly sorted instatExtras. This should help catch the errors after future updates, and also catch errors we have in there now that we've missed.
